version: '3.8'

services:
  # ML Services (FastAPI)
  ml-api:
    build: .
    container_name: sabq-ml-api
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=info
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - sabq-network

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: sabq-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - sabq-network
    command: redis-server --appendonly yes

  # PostgreSQL Database (if needed for ML data)
  postgres:
    image: postgres:15-alpine
    container_name: sabq-postgres-ml
    environment:
      POSTGRES_DB: sabq_ml
      POSTGRES_USER: sabq_user
      POSTGRES_PASSWORD: sabq_password
    ports:
      - "5433:5432"  # Different port to avoid conflicts
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - sabq-network

  # Nginx for load balancing (optional)
  nginx:
    image: nginx:alpine
    container_name: sabq-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ml-api
    restart: unless-stopped
    networks:
      - sabq-network

# Networks
networks:
  sabq-network:
    driver: bridge

# Volumes
volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local 